### ISSUE TITLE
Create folder and add DSA notes in java 

### ISSUE THREAD

**Issue by mindexpert7546** [mindexpert7546/Learn-DSA#3]

**Comment by neeraj3199** [comment]
i can do that easily please assign it to me

**Comment by mindexpert7546** [comment]
yeah sure assign @neeraj3199

**Comment by jawadkhanpk** [comment]
@mindexpert7546 Hey, I have some handouts of Java, please assign this issue to me so that I can add it to a folder Thanks.

**Comment by mindexpert7546** [comment]
Yeah sure you can go with them @jawadkhanpk

**Comment by jawadkhanpk** [comment]
please assign
@mindexpert7546

**Comment by mindexpert7546** [comment]
ok assign to @jawadkhanpk and unassing to @neeraj3199 (because no response )

**Comment by mindexpert7546** [comment]
ok assign to @jawadkhanpk and unassing to @neeraj3199 (because no response )

**Comment by jawadkhanpk** [comment]
please see and merge it to main branch, Thanks

**Comment by mindexpert7546** [comment]
do continue @neeraj3199
